# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 5cc6e23f78babb3856ecebbd12cc962411989a8e

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/38/
Content-Type: application/json
Authorization: Token c3e8514e3d23042ef2954eaf500aabb869c7a8e6

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

#admin {1}  5cc6e23f78babb3856ecebbd12cc962411989a8e
#admin2 {2} c3e8514e3d23042ef2954eaf500aabb869c7a8e6